server: 
  port: 9009
spring: 
  application:  
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.1.132

aliyun:
  sms:
      accessKeyId:  LTAIfzc3nn7VVWJM
      accessKeySecret: pF4Qex89GLv0b8farsamJEvVKxwRYZ

      template_code: SMS_164279140
      sign_name: 灵山网